{% set name = "groundingdino-py" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/groundingdino-py-{{ version }}.tar.gz
  sha256: 23de56af498b7cdcc024eb1062fc3179e3cc4dacd92adbfb625097065377700f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch
    - torchvision
    - transformers
    - addict
    - yapf
    - timm
    - numpy
    - opencv
    - supervision ==0.6.0
    - pycocotools

test:
  imports:
    - groundingdino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/GroundingDINO
  summary: open-set object detector
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
